spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: ujjwal
    password: ujjwal
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
  file:
    name: logs/${spring.application.name}.log   #Spring boot interpret relative path based on my application started.
  logback:
    rollingpolicy:
      max-file-size: 5MB  #upto use 5MB
      max-history: 7  # keep the log last 7 days

management:
  endpoints:
    web:
      exposure:
        include: shutdown
  endpoint:
    shutdown:
      enabled: true