spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecom_user
      database: ecom_user

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true



management:
  endpoints:
    web:
      exposure:
        include: "*"